name: Caturix
version: @version@
author: Ninjoh
api-version: 1.20
main: com.ironveilrp.caturix.spigot.CaturixSpigot
libraries:
  - com.google.guava:guava:33.0.0-jre
#  - org.jetbrains.kotlin:kotlin-stdlib:1.9.21
